# Generated by Django 4.2.2 on 2023-06-22 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ecole_data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('principal_name', models.CharField(max_length=40)),
                ('url', models.CharField(max_length=70)),
            ],
        ),
    ]
