# Generated by Django 4.2.2 on 2023-06-24 13:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login_handler', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='classes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('level', models.CharField(choices=[('0', 'التحضيري'), ('1', 'الأولى'), ('2', 'الثانية'), ('3', 'الثالثة'), ('4', 'الرابعة'), ('5', 'الخامسة'), ('6', 'السادسة')], max_length=1)),
                ('count', models.CharField(max_length=3)),
                ('male_count', models.CharField(max_length=3)),
                ('female_count', models.CharField(max_length=3)),
                ('next_class_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='login_handler.classes')),
            ],
        ),
        migrations.CreateModel(
            name='eleves',
            fields=[
                ('eid', models.IntegerField(primary_key=True, serialize=False)),
                ('id', models.BigIntegerField()),
                ('nom', models.CharField(max_length=40)),
                ('prenom', models.CharField(max_length=40)),
                ('sexe', models.CharField(choices=[('m', 'ذكر'), ('f', 'أنثى')], max_length=1)),
                ('moyen', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('class_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='login_handler.classes')),
            ],
        ),
    ]
