# Generated by Django 4.2.2 on 2023-06-24 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_handler', '0004_alter_eleves_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eleves',
            name='id',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
