# Generated by Django 4.2.2 on 2023-07-02 05:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login_handler', '0008_classes_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profs',
            name='id',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='matieres',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('classe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login_handler.classes')),
                ('prof', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login_handler.profs')),
            ],
        ),
    ]
