# Generated by Django 4.2.2 on 2023-07-02 09:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login_handler', '0009_alter_profs_id_matieres'),
    ]

    operations = [
        migrations.RenameField(
            model_name='matieres',
            old_name='classe',
            new_name='saisie_classe',
        ),
        migrations.RemoveField(
            model_name='matieres',
            name='prof',
        ),
        migrations.AddField(
            model_name='matieres',
            name='saisie_matiere_id',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='matieres',
            name='saisie_prof',
            field=models.ForeignKey(blank=True, default=0, on_delete=django.db.models.deletion.CASCADE, to='login_handler.profs'),
        ),
    ]
