# Generated by Django 4.2.2 on 2023-07-02 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_handler', '0010_rename_classe_matieres_saisie_classe_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classes',
            name='name',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='matieres',
            name='name',
            field=models.CharField(max_length=60),
        ),
    ]
