# Generated by Django 4.2.2 on 2023-07-02 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login_handler', '0013_alter_matieres_saisie_prof'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='matieres',
            unique_together={('name', 'saisie_classe')},
        ),
    ]
