# Generated by Django 4.2.2 on 2023-07-02 09:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login_handler', '0014_alter_matieres_unique_together'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='matieres',
            options={'ordering': ['saisie_classe', 'saisie_matiere_id']},
        ),
    ]
