# Generated by Django 4.2.2 on 2023-07-02 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_handler', '0015_alter_matieres_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='profs',
            name='is_old',
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
    ]
