# Generated by Django 4.2.2 on 2023-07-17 07:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login_handler', '0016_profs_is_old'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profs',
            old_name='is_old',
            new_name='is_active',
        ),
    ]
