# Generated by Django 4.2.2 on 2023-07-20 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_handler', '0017_rename_is_old_profs_is_active'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='classes',
            options={'ordering': ['level', 'name']},
        ),
        migrations.AlterModelOptions(
            name='eleves',
            options={'ordering': ['nom', 'prenom']},
        ),
        migrations.AddField(
            model_name='eleves',
            name='is_graduated',
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
    ]
