# Generated by Django 4.2.2 on 2023-07-20 13:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login_handler', '0018_alter_classes_options_alter_eleves_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='eleves',
            name='next_class_id',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='next_students', to='login_handler.classes'),
        ),
        migrations.AlterField(
            model_name='eleves',
            name='class_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='students', to='login_handler.classes'),
        ),
    ]
