# Generated by Django 4.2.2 on 2023-07-23 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login_handler', '0020_eleves_date_naissance_matieres2'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='matieres2',
            unique_together=set(),
        ),
    ]
