# Generated by Django 4.2.2 on 2023-07-23 17:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login_handler', '0021_alter_matieres2_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='matieres2',
            unique_together={('field', 'saisie_classe')},
        ),
    ]
