# Generated by Django 4.2.2 on 2023-07-24 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_handler', '0022_alter_matieres2_unique_together'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='matieres',
            options={'ordering': ['saisie_classe']},
        ),
        migrations.AlterModelOptions(
            name='matieres2',
            options={'ordering': ['saisie_classe', 'saisie_matiere_id']},
        ),
        migrations.AlterUniqueTogether(
            name='matieres',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='matieres2',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='matieres',
            name='field',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='matieres2',
            name='name',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='matieres2',
            name='saisie_matiere_id',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterUniqueTogether(
            name='matieres',
            unique_together={('field', 'saisie_classe')},
        ),
        migrations.AlterUniqueTogether(
            name='matieres2',
            unique_together={('name', 'saisie_classe')},
        ),
        migrations.RemoveField(
            model_name='matieres',
            name='name',
        ),
        migrations.RemoveField(
            model_name='matieres',
            name='saisie_matiere_id',
        ),
        migrations.RemoveField(
            model_name='matieres2',
            name='field',
        ),
    ]
