# Generated by Django 4.2.2 on 2023-07-27 12:58

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('login_handler', '0023_alter_matieres_options_alter_matieres2_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eleves',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
