# Generated by Django 4.2.2 on 2023-07-27 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_handler', '0024_alter_eleves_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eleves',
            name='id',
            field=models.BigIntegerField(blank=True, default=0, null=True),
        ),
    ]
