# Generated by Django 4.2.2 on 2023-07-27 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_handler', '0025_alter_eleves_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eleves',
            name='eid',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='eleves',
            name='id',
            field=models.BigIntegerField(default=10, primary_key=True, serialize=False),
        ),
    ]
