# Generated by Django 4.2.2 on 2023-07-29 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_handler', '0026_alter_eleves_eid_alter_eleves_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ecole_data',
            name='name',
        ),
        migrations.RemoveField(
            model_name='ecole_data',
            name='principal_name',
        ),
        migrations.AddField(
            model_name='ecole_data',
            name='principal_nom',
            field=models.CharField(default='', max_length=40),
        ),
        migrations.AddField(
            model_name='ecole_data',
            name='principal_prenom',
            field=models.CharField(default='', max_length=40),
        ),
        migrations.AddField(
            model_name='ecole_data',
            name='school_name',
            field=models.CharField(default='', max_length=40),
        ),
    ]
