# Generated by Django 4.2.2 on 2023-07-29 11:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login_handler', '0027_remove_ecole_data_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ecole_data',
            old_name='principal_nom',
            new_name='pr_nom',
        ),
        migrations.RenameField(
            model_name='ecole_data',
            old_name='principal_prenom',
            new_name='pr_prenom',
        ),
    ]
