# Generated by Django 4.2.2 on 2023-07-29 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_handler', '0028_rename_principal_nom_ecole_data_pr_nom_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ecole_data',
            name='pr_nom',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='ecole_data',
            name='pr_prenom',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='ecole_data',
            name='school_name',
            field=models.CharField(max_length=50),
        ),
    ]
