# Generated by Django 4.2.2 on 2023-07-29 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_handler', '0029_alter_ecole_data_pr_nom_alter_ecole_data_pr_prenom_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ecole_data2',
            fields=[
                ('sid', models.IntegerField(primary_key=True, serialize=False)),
                ('school_name', models.CharField(max_length=50)),
                ('pr_nom', models.CharField(max_length=50)),
                ('pr_prenom', models.CharField(max_length=50)),
                ('url', models.CharField(max_length=70)),
            ],
        ),
    ]
