# Generated by Django 4.2.2 on 2023-07-29 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login_handler', '0030_ecole_data2'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ecole_data',
        ),
    ]
