# Generated by Django 4.2.2 on 2023-07-29 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login_handler', '0031_delete_ecole_data'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Ecole_data2',
            new_name='Ecole_data',
        ),
    ]
