# Generated by Django 4.2.2 on 2023-07-31 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_handler', '0032_rename_ecole_data2_ecole_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='eleves',
            name='resultat',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
