# Generated by Django 4.2.2 on 2023-07-31 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login_handler', '0034_eleves2'),
    ]

    operations = [
        migrations.DeleteModel(
            name='eleves',
        ),
    ]
