# Generated by Django 4.2.2 on 2023-07-31 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login_handler', '0036_eleves'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Eleves',
        ),
    ]
