# Generated by Django 4.2.2 on 2023-07-31 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login_handler', '0037_delete_eleves'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Eleves2',
            new_name='Eleves',
        ),
    ]
