# Generated by Django 4.2.2 on 2023-07-31 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_handler', '0039_alter_eleves_class_id_alter_eleves_next_class_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='excution_time',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
            ],
        ),
    ]
