# Generated by Django 4.2.2 on 2023-08-14 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_handler', '0040_excution_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='ElevesArrives',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=40)),
                ('prenom', models.CharField(max_length=40)),
                ('prev_ecole', models.CharField(max_length=40)),
                ('date_naissance', models.DateField(blank=True, null=True)),
                ('date_sortie', models.DateField(blank=True, null=True)),
                ('arriv_sorti', models.CharField(blank=True, max_length=25, null=True)),
            ],
        ),
    ]
