# Generated by Django 4.2.2 on 2023-08-14 08:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login_handler', '0041_elevesarrives'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ElevesArrives',
            new_name='ElevesTransfer',
        ),
    ]
