# Generated by Django 4.2.2 on 2023-08-14 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_handler', '0042_rename_elevesarrives_elevestransfer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='elevestransfer',
            old_name='prev_ecole',
            new_name='prev_new_ecole',
        ),
        migrations.AlterField(
            model_name='elevestransfer',
            name='arriv_sorti',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
    ]
