# Generated by Django 4.2.2 on 2023-08-15 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_handler', '0043_rename_prev_ecole_elevestransfer_prev_new_ecole_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='sexeEleves',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=40)),
                ('male', models.BooleanField(default=False)),
                ('female', models.BooleanField(default=False)),
            ],
        ),
    ]
