# Generated by Django 4.2.2 on 2023-08-15 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_handler', '0046_del1_dre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ecole_data',
            name='url',
            field=models.CharField(max_length=90),
        ),
    ]
