# Generated by Django 4.2.2 on 2023-08-15 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_handler', '0047_alter_ecole_data_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ecole_data',
            name='url',
            field=models.CharField(max_length=100),
        ),
    ]
