# Generated by Django 4.2.2 on 2023-08-15 07:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login_handler', '0048_alter_ecole_data_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='ecole_data',
            name='del1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='login_handler.del1'),
        ),
        migrations.AddField(
            model_name='ecole_data',
            name='dre',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='login_handler.dre'),
        ),
    ]
