# Generated by Django 4.2.2 on 2023-08-15 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_handler', '0049_ecole_data_del1_ecole_data_dre'),
    ]

    operations = [
        migrations.AddField(
            model_name='ecole_data',
            name='stat_school_name',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
