# Generated by Django 4.2.2 on 2023-08-15 12:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login_handler', '0051_alter_ecole_data_del1_alter_ecole_data_dre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ecole_data',
            name='del1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='login_handler.del1'),
        ),
        migrations.AlterField(
            model_name='ecole_data',
            name='dre',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='login_handler.dre'),
        ),
        migrations.AlterField(
            model_name='ecole_data',
            name='stat_school_name',
            field=models.CharField(blank=True, default=None, max_length=50),
        ),
    ]
