# Generated by Django 4.2.2 on 2023-08-15 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_handler', '0053_alter_ecole_data_stat_school_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ecole_data',
            name='stat_school_name',
            field=models.CharField(blank=True, default=None, max_length=50),
        ),
    ]
