# Generated by Django 4.2.2 on 2023-08-16 15:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login_handler', '0055_alter_ecole_data_stat_school_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExcelData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_prenom', models.CharField(max_length=50)),
                ('eleve_id', models.BigIntegerField(blank=True, null=True)),
                ('prev_ecole', models.CharField(max_length=50)),
                ('level', models.PositiveSmallIntegerField()),
                ('next_ecole', models.CharField(max_length=50)),
                ('dre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='login_handler.dre')),
            ],
        ),
    ]
