# Generated by Django 4.2.2 on 2023-08-18 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login_handler', '0056_exceldata'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Eleves2',
        ),
    ]
