# Generated by Django 4.2.2 on 2023-08-18 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_handler', '0057_delete_eleves2'),
    ]

    operations = [
        migrations.RenameField(
            model_name='excution_time',
            old_name='text',
            new_name='funct',
        ),
        migrations.AddField(
            model_name='excution_time',
            name='time',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
    ]
