# Generated by Django 4.2.2 on 2023-08-18 11:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login_handler', '0059_excution_time_id2'),
    ]

    operations = [
        migrations.DeleteModel(
            name='excution_time',
        ),
    ]
