# Generated by Django 4.2.2 on 2023-08-18 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_handler', '0060_delete_excution_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='excution_time',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id2', models.PositiveSmallIntegerField()),
                ('funct', models.TextField()),
                ('time', models.TextField()),
            ],
        ),
    ]
