# Generated by Django 4.2.2 on 2023-08-18 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_handler', '0061_excution_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='excution_time',
            name='funct',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='excution_time',
            name='time',
            field=models.TextField(blank=True, null=True),
        ),
    ]
