# Generated by Django 4.2.2 on 2023-08-18 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_handler', '0062_alter_excution_time_funct_alter_excution_time_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='Logins',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sid', models.PositiveSmallIntegerField()),
                ('field', models.TextField(blank=True, null=True)),
                ('val', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
