# Generated by Django 4.2.2 on 2023-08-19 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_handler', '0063_logins'),
    ]

    operations = [
        migrations.AddField(
            model_name='elevestransfer',
            name='level',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='elevestransfer',
            name='sexe',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
