# Generated by Django 4.2.2 on 2023-08-21 11:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login_handler', '0065_elevestransfer_is_graduated'),
    ]

    operations = [
        migrations.AddField(
            model_name='classes',
            name='ecole',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='login_handler.ecole_data'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='eleves',
            name='ecole',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='login_handler.ecole_data'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='elevestransfer',
            name='ecole',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='login_handler.ecole_data'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='excution_time',
            name='ecole',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='login_handler.ecole_data'),
        ),
        migrations.AddField(
            model_name='logins',
            name='ecole',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='login_handler.ecole_data'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='matieres',
            name='ecole',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='login_handler.ecole_data'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profs',
            name='ecole',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='login_handler.ecole_data'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Matieres2',
        ),
    ]
