# Generated by Django 4.2.2 on 2023-08-21 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_handler', '0067_alter_classes_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='classes',
            name='id_1',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
