# Generated by Django 4.2.2 on 2023-08-21 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login_handler', '0068_classes_id_1'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classes',
            name='id_1',
        ),
    ]
