# Generated by Django 4.2.2 on 2023-08-21 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login_handler', '0070_rename_id_classes_id_1_classes_id_3'),
    ]

    operations = [
        migrations.RenameField(
            model_name='classes',
            old_name='id_3',
            new_name='id',
        ),
    ]
