# Generated by Django 4.2.2 on 2023-08-21 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_handler', '0072_alter_classes_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='eleves',
            name='id_1',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
