# Generated by Django 4.2.2 on 2023-08-21 14:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login_handler', '0074_alter_eleves_eid_alter_eleves_id_1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eleves',
            name='next_class_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='next_students', to='login_handler.classes'),
        ),
    ]
