# Generated by Django 4.2.2 on 2023-08-21 14:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login_handler', '0076_alter_eleves_next_class_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eleves',
            name='class_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='login_handler.classes'),
        ),
        migrations.AlterField(
            model_name='eleves',
            name='next_class_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='next_class', to='login_handler.classes'),
        ),
    ]
