# Generated by Django 4.2.2 on 2023-08-21 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login_handler', '0077_alter_eleves_class_id_alter_eleves_next_class_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='eleves',
            old_name='class_id',
            new_name='classe',
        ),
        migrations.RenameField(
            model_name='eleves',
            old_name='next_class_id',
            new_name='next_class',
        ),
    ]
