# Generated by Django 4.2.2 on 2023-08-21 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_handler', '0078_rename_class_id_eleves_classe_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eleves',
            name='id_1',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
