# Generated by Django 4.2.2 on 2023-08-21 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_handler', '0079_alter_eleves_id_1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classes',
            name='id_1',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
