# Generated by Django 4.2.2 on 2023-08-22 08:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login_handler', '0080_alter_classes_id_1'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='matieres',
            name='saisie_prof',
        ),
    ]
