# Generated by Django 4.2.2 on 2023-08-22 08:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login_handler', '0081_remove_matieres_saisie_prof'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='profs',
            new_name='Profs2',
        ),
    ]
