# Generated by Django 4.2.2 on 2023-08-22 09:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login_handler', '0083_rename_ecole_profs2_ecole2'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profs',
            fields=[
                ('id_1', models.AutoField(primary_key=True, serialize=False)),
                ('eid', models.IntegerField()),
                ('id', models.BigIntegerField(blank=True, null=True)),
                ('nom', models.CharField(max_length=40)),
                ('prenom', models.CharField(max_length=40)),
                ('is_active', models.BooleanField(blank=True, default=None, null=True)),
                ('ecole', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='login_handler.ecole_data')),
            ],
        ),
    ]
