# Generated by Django 4.2.2 on 2023-08-22 09:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login_handler', '0084_profs'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profs',
            old_name='id_1',
            new_name='PK',
        ),
    ]
