# Generated by Django 4.2.2 on 2023-08-22 09:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login_handler', '0085_rename_id_1_profs_pk'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profs2',
        ),
    ]
