# Generated by Django 4.2.2 on 2023-08-22 09:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login_handler', '0086_delete_profs2'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profs',
            old_name='id',
            new_name='pid',
        ),
    ]
