# Generated by Django 4.2.2 on 2023-08-22 09:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login_handler', '0087_rename_id_profs_pid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profs',
            old_name='PK',
            new_name='id',
        ),
    ]
