# Generated by Django 4.2.2 on 2023-08-22 09:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login_handler', '0089_rename_id_classes_cid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='classes',
            old_name='id_1',
            new_name='id',
        ),
    ]
