# Generated by Django 4.2.2 on 2023-08-22 09:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login_handler', '0090_rename_id_1_classes_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='matieres',
            name='prof',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='login_handler.profs'),
        ),
    ]
