# Generated by Django 4.2.2 on 2023-08-22 09:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login_handler', '0091_matieres_prof'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='matieres',
            unique_together=set(),
        ),
    ]
