# Generated by Django 4.2.2 on 2023-08-22 09:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login_handler', '0092_alter_matieres_unique_together'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='logins',
            name='sid',
        ),
    ]
