# Generated by Django 4.2.2 on 2023-08-22 09:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login_handler', '0093_remove_logins_sid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='eleves',
            old_name='classe',
            new_name='classe22',
        ),
        migrations.RenameField(
            model_name='eleves',
            old_name='next_class',
            new_name='next_class22',
        ),
    ]
