# Generated by Django 4.2.2 on 2023-08-22 10:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login_handler', '0097_delete_eleves2'),
    ]

    operations = [
        migrations.CreateModel(
            name='Eleves2',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('eid', models.IntegerField()),
                ('uid', models.BigIntegerField(blank=True, null=True)),
                ('nom', models.CharField(max_length=40)),
                ('prenom', models.CharField(max_length=40)),
                ('sexe', models.CharField(max_length=10)),
                ('date_naissance', models.DateField(blank=True, null=True)),
                ('moyen', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('resultat', models.CharField(blank=True, max_length=25, null=True)),
                ('is_graduated', models.BooleanField(blank=True, default=None, null=True)),
                ('classe', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='login_handler.classes')),
                ('ecole', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='login_handler.ecole_data')),
                ('next_class', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='next_class', to='login_handler.classes')),
            ],
            options={
                'ordering': ['nom', 'prenom'],
            },
        ),
    ]
