# Generated by Django 4.2.2 on 2023-08-22 10:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login_handler', '0098_eleves2'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Eleves',
        ),
    ]
