# Generated by Django 4.2.2 on 2023-08-22 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login_handler', '0100_rename_eleves2_eleves'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='matieres',
            options={'ordering': ['classe']},
        ),
        migrations.RenameField(
            model_name='matieres',
            old_name='saisie_classe',
            new_name='classe',
        ),
    ]
