# Generated by Django 4.2.2 on 2023-08-22 10:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login_handler', '0101_alter_matieres_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ElevesTransfer2',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('uid', models.BigIntegerField()),
                ('nom', models.CharField(max_length=40)),
                ('prenom', models.CharField(max_length=40)),
                ('prev_new_ecole', models.CharField(max_length=40)),
                ('date_naissance', models.DateField(blank=True, null=True)),
                ('date_sortie', models.DateField(blank=True, null=True)),
                ('arriv_sorti', models.BooleanField()),
                ('sexe', models.CharField(blank=True, max_length=10, null=True)),
                ('level', models.CharField(blank=True, max_length=10, null=True)),
                ('is_graduated', models.BooleanField(blank=True, max_length=10, null=True)),
                ('ecole', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='login_handler.ecole_data')),
            ],
        ),
    ]
