# Generated by Django 4.2.2 on 2023-08-22 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login_handler', '0102_elevestransfer2'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ElevesTransfer',
        ),
    ]
