# Generated by Django 4.2.2 on 2023-08-22 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login_handler', '0104_rename_elevestransfer2_elevestransfer'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='classes',
            unique_together={('cid', 'ecole')},
        ),
        migrations.AlterUniqueTogether(
            name='eleves',
            unique_together={('eid', 'ecole')},
        ),
    ]
