# Generated by Django 4.2.2 on 2023-08-22 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_handler', '0105_alter_classes_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profs',
            name='is_active',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
