# Generated by Django 4.2.2 on 2023-08-22 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_handler', '0106_alter_profs_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='elevestransfer',
            name='uid',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
