# Generated by Django 4.2.2 on 2023-08-26 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_handler', '0108_ecole_data_nbr_elev'),
    ]

    operations = [
        migrations.AddField(
            model_name='ecole_data',
            name='virgin',
            field=models.BooleanField(default=False),
        ),
    ]
