# Generated by Django 4.2.2 on 2023-08-27 20:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login_handler', '0113_remove_classes_count_remove_classes_female_count_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eleves',
            name='next_class',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='next_class', to='login_handler.classes'),
        ),
    ]
